[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200

build_src_filter = +<main.cpp> +<dbp.cpp> +<hand_placement.cpp> +<pump_control.cpp> +<tof.cpp> +<compression_analysis.cpp>
; build_src_filter = +<LoadCellCode_V1.cpp>

lib_deps =
    stm32duino/STM32duino VL53L4CD
    Bogde/HX711